In [1]:
import datetime

current_time = datetime.datetime.now()
print("Current time is:", current_time)

Current time is: 2024-02-14 19:15:16.673112

In [2]:
current_time = datetime.datetime.now().time()
print("Current time is:", current_time)

Current time is: 19:16:13.095801

In [4]:
import datetime

# Define the two times
time1 = datetime.datetime(19:15:16.673112)  # Example time 1
time2 = datetime.datetime(19:16:13.095801)  # Example time 2

# Calculate the difference
time_difference = time2 - time1

print("Time difference:", time_difference)

SyntaxError: invalid syntax (665071412.py, line 4)

In [5]:
import datetime

# Define the two times
time1 = datetime.time(12, 30)  # Example time 1
time2 = datetime.time(14, 45)  # Example time 2

# Calculate the difference
time_difference_hours = time2.hour - time1.hour
time_difference_minutes = time2.minute - time1.minute

# Adjust minutes if negative
if time_difference_minutes < 0:
    time_difference_hours -= 1
    time_difference_minutes += 60

print("Time difference:", time_difference_hours, "hours and", time_difference_minutes, "minutes")

Time difference: 2 hours and 15 minutes

In [10]:
timea = datetime.time(19, 15, 16)
timeb = datetime.time(19, 16, 13)
print(timeb - timea)

TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'

In [2]:
import csv
from faker import Faker
import random
from datetime import datetime, timedelta

# Initialize Faker to generate random data
fake = Faker()

# Define the number of rows
num_rows = 200000

# Define possible values for categorical variables
premium_frequencies = ['A', 'B', 'C']  # Example premium frequencies
product_codes = ['301', '302', '303']  # Example product codes
product_names = ['Product A', 'Product B', 'Product C']  # Example product names
insured_sexes = ['M', 'F']  # Example sexes
policy_statuses = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'REINSTATED']  # Example policy statuses

# Define a function to generate a random date within a range
def random_date(start_date, end_date):
    return start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

# Define the start and end dates for issuance and commencement
start_issuance_date = datetime(2010, 1, 1)
end_issuance_date = datetime(2022, 12, 31)
start_commencement_date = datetime(2010, 1, 1)
end_commencement_date = datetime(2022, 12, 31)

# Open a CSV file to write the dummy data
with open('dummy_data.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    
    # Write the header row
    writer.writerow(["PROPOSAL_NO", "POLICY_NO", "PREMIUM_FREQUENCY", "PPR_PRODCD", "PRODUCT_NAME",
                     "ISSUANCE_DATE", "COMMENCEMENT_DATE", "NETPREMIUM", "BASIC_SUMASSURED",
                     "INSURED_SEX", "INSURED_DOB", "COVERMULTIPLE", "BENEFIT_TERM", "BASIC_CASH_VALUE",
                     "Group Code", "POLICY_STATUS", "Status_code"])
    
    # Generate and write dummy data for the specified number of rows
    for _ in range(num_rows):
        issuance_date = random_date(start_issuance_date, end_issuance_date)
        commencement_date = random_date(start_commencement_date, end_commencement_date)
        
        writer.writerow([
            fake.random_number(digits=9),  # Proposal number
            fake.random_number(digits=9),  # Policy number
            random.choice(premium_frequencies),  # Premium frequency
            random.choice(product_codes),  # Product code
            random.choice(product_names),  # Product name
            issuance_date.strftime('%d/%m/%Y'),  # Issuance date
            commencement_date.strftime('%d/%m/%Y'),  # Commencement date
            fake.random_number(digits=6),  # Net premium
            fake.random_number(digits=6),  # Basic sum assured
            random.choice(insured_sexes),  # Insured sex
            fake.date_of_birth(minimum_age=18, maximum_age=80).strftime('%d/%m/%Y'),  # Insured DOB
            fake.random_number(digits=5),  # Cover multiple
            fake.random_number(digits=2),  # Benefit term
            fake.random_number(digits=9),  # Basic cash value
            fake.random_letter() + '-' + str(fake.random_number(digits=2)),  # Group code
            random.choice(policy_statuses),  # Policy status
            fake.random_number(digits=1)  # Status code
        ])

In [2]:
pip install faker

Collecting faker
  Obtaining dependency information for faker from https://files.pythonhosted.org/packages/be/de/8bd27eb39eda9e06803b8ac89ae32edff0b7d206f4b69cd2f558ae24620e/Faker-23.2.0-py3-none-any.whl.metadata
  Downloading Faker-23.2.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\user\anaconda3\lib\site-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-23.2.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 495.5 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/1.7 MB 1.7 MB/s eta 0:00:01
   ----------- ---------------------------- 0.5/1.7 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 1.4/1.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 7.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-23.2.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import csv
from faker import Faker
import random
from datetime import datetime, timedelta

# Initialize Faker to generate random data
fake = Faker()

# Define the number of rows
num_rows = 200000

# Define a function to calculate the cover multiple based on the provided formula
def calculate_cover_multiple(commencement_date, dob):
    days = (commencement_date - dob).days + 1
    years = days / 365.25
    return min(round(years), 100)  # Ensure the value does not exceed 100

# Define the start and end dates for issuance and commencement
start_issuance_date = datetime(2010, 1, 1)
end_issuance_date = datetime(2022, 12, 31)
start_commencement_date = datetime(2010, 1, 1)
end_commencement_date = datetime(2022, 12, 31)

# Open a CSV file to write the dummy data
with open('dummy_dataII.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    
    # Write the header row
    writer.writerow(["PROPOSAL_NO", "POLICY_NO", "PREMIUM_FREQUENCY", "PPR_PRODCD", "PRODUCT_NAME",
                     "ISSUANCE_DATE", "COMMENCEMENT_DATE", "NETPREMIUM", "BASIC_SUMASSURED",
                     "INSURED_SEX", "INSURED_DOB", "COVERMULTIPLE", "BENEFIT_TERM", "BASIC_CASH_VALUE",
                     "Group Code", "POLICY_STATUS", "Status_code"])
    
    # Generate and write dummy data for the specified number of rows
    for _ in range(num_rows):
        issuance_date = fake.date_between(start_date=start_issuance_date, end_date=end_issuance_date)
        commencement_date = fake.date_between(start_date=start_commencement_date, end_date=end_commencement_date)
        dob = fake.date_of_birth(minimum_age=18, maximum_age=80)
        
        # Calculate the cover multiple
        cover_multiple = calculate_cover_multiple(commencement_date, dob)
        
        writer.writerow([
            fake.random_number(digits=9),  # Proposal number
            fake.random_number(digits=9),  # Policy number
            random.choice(['A', 'B', 'C']),  # Premium frequency
            random.choice(['301', '302', '303']),  # Product code
            random.choice(['Product A', 'Product B', 'Product C']),  # Product name
            issuance_date.strftime('%d/%m/%Y'),  # Issuance date
            commencement_date.strftime('%d/%m/%Y'),  # Commencement date
            fake.random_number(digits=6),  # Net premium
            fake.random_number(digits=6),  # Basic sum assured
            random.choice(['M', 'F']),  # Insured sex
            dob.strftime('%d/%m/%Y'),  # Insured DOB
            cover_multiple,  # Cover multiple
            fake.random_number(digits=2),  # Benefit term
            fake.random_number(digits=9),  # Basic cash value
            fake.random_letter() + '-' + str(fake.random_number(digits=2)),  # Group code
            random.choice(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'REINSTATED']),  # Policy status
            fake.random_number(digits=1)  # Status code
        ])

In [9]:
from datetime import datetime
date_int = 26628
def int_to_date(date_int):
    year = date_int // 10000
    month = (date_int // 100) % 100
    day = date_int % 100
    
    return datetime(year, month, day).strftime("%d-%m-%Y")

int_to_date(26628)

ValueError: month must be in 1..12

In [1]:
import pandas as pd

# Read the Excel file into a pandas DataFrame
excel_file = "data.xlsx"  # Replace "your_excel_file.xlsx" with the path to your Excel file
df = pd.read_excel(excel_file)

# Specify the path where you want to save the CSV file
csv_file = "output_file.csv"  # Change "output_file.csv" to the desired CSV file path

# Save the DataFrame to a CSV file
df.to_csv(csv_file, index=False)  # Set index=False to avoid saving row numbers as a column in the CSV file

In [23]:
import numpy as np

# Example function for calculation
def calculate_value(x):
    return x**2  # Square of the input value

# Method 1: Vectorized operation
start = 0
end = 10
num_elements = 10

x_values = np.linspace(start, end, num_elements, dtype=int, endpoint=False)
print(x_values)
my_array = calculate_value(x_values)

print("Method 1 - Vectorized operation:")
print(my_array)

[0 1 2 3 4 5 6 7 8 9]
Method 1 - Vectorized operation:
[ 0  1  4  9 16 25 36 49 64 81]

In [12]:
my_array[6]

36

In [2]:
import time

def squaring():
    start_time = time.time()
    x = []
    for i in range(1, 200001):
        val = i ** 2
        x.append(val)
    print("Total Time:", (time.time() - start_time))
    print(len(x))
    return x

squaring()

Total Time: 0.027985572814941406
200000

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449,
 20736,
 21025,
 21316,
 21609,
 21904,
 22201,
 22500,
 22801,
 23104,
 23409,
 23716,
 24025,
 24336,
 24649,
 24964,
 25281,
 25600,
 25921,
 26244,
 26569,
 26896,
 27225,
 27556,
 27889,
 28224,
 28561,
 28900,
 29241,
 29584,
 29929,
 30276,
 30625,
 30976,
 31329,
 31684,
 32041,
 32400,
 32761,
 33124,
 33489,
 33856,
 34225,
 34596,
 34969,
 35344,
 35721,
 36100,
 36481,
 36864,
 37249,
 37636,
 38025,
 38416,
 38809,
 39204,
 39601,
 40000,
 40401,
 40804,
 41209,
 41616,
 42025,
 42436,
 42849,
 43264,
 43681,
 44100,
 44521,
 44944,
 45369,
 45796,
 46225,
 46656,
 47089,
 47524,
 47961,
 48400,
 48841,
 49284,
 49729,
 50176,
 50625,
 51076,
 51529,
 51984,
 52441,
 52900,
 53361,
 53824,
 54289,
 54756,
 55225,
 55696,
 56169,
 56644,
 57121,
 57600,
 58081,
 58564,
 59049,
 59536,
 60025,
 60516,
 61009,
 61504,
 62001,
 62500,
 63001,
 63504,
 64009,
 64516,
 65025,
 65536,
 66049,
 66564,
 67081,
 67600,
 68121,
 68644,
 69169,
 69696,
 70225,
 70756,
 71289,
 71824,
 72361,
 72900,
 73441,
 73984,
 74529,
 75076,
 75625,
 76176,
 76729,
 77284,
 77841,
 78400,
 78961,
 79524,
 80089,
 80656,
 81225,
 81796,
 82369,
 82944,
 83521,
 84100,
 84681,
 85264,
 85849,
 86436,
 87025,
 87616,
 88209,
 88804,
 89401,
 90000,
 90601,
 91204,
 91809,
 92416,
 93025,
 93636,
 94249,
 94864,
 95481,
 96100,
 96721,
 97344,
 97969,
 98596,
 99225,
 99856,
 100489,
 101124,
 101761,
 102400,
 103041,
 103684,
 104329,
 104976,
 105625,
 106276,
 106929,
 107584,
 108241,
 108900,
 109561,
 110224,
 110889,
 111556,
 112225,
 112896,
 113569,
 114244,
 114921,
 115600,
 116281,
 116964,
 117649,
 118336,
 119025,
 119716,
 120409,
 121104,
 121801,
 122500,
 123201,
 123904,
 124609,
 125316,
 126025,
 126736,
 127449,
 128164,
 128881,
 129600,
 130321,
 131044,
 131769,
 132496,
 133225,
 133956,
 134689,
 135424,
 136161,
 136900,
 137641,
 138384,
 139129,
 139876,
 140625,
 141376,
 142129,
 142884,
 143641,
 144400,
 145161,
 145924,
 146689,
 147456,
 148225,
 148996,
 149769,
 150544,
 151321,
 152100,
 152881,
 153664,
 154449,
 155236,
 156025,
 156816,
 157609,
 158404,
 159201,
 160000,
 160801,
 161604,
 162409,
 163216,
 164025,
 164836,
 165649,
 166464,
 167281,
 168100,
 168921,
 169744,
 170569,
 171396,
 172225,
 173056,
 173889,
 174724,
 175561,
 176400,
 177241,
 178084,
 178929,
 179776,
 180625,
 181476,
 182329,
 183184,
 184041,
 184900,
 185761,
 186624,
 187489,
 188356,
 189225,
 190096,
 190969,
 191844,
 192721,
 193600,
 194481,
 195364,
 196249,
 197136,
 198025,
 198916,
 199809,
 200704,
 201601,
 202500,
 203401,
 204304,
 205209,
 206116,
 207025,
 207936,
 208849,
 209764,
 210681,
 211600,
 212521,
 213444,
 214369,
 215296,
 216225,
 217156,
 218089,
 219024,
 219961,
 220900,
 221841,
 222784,
 223729,
 224676,
 225625,
 226576,
 227529,
 228484,
 229441,
 230400,
 231361,
 232324,
 233289,
 234256,
 235225,
 236196,
 237169,
 238144,
 239121,
 240100,
 241081,
 242064,
 243049,
 244036,
 245025,
 246016,
 247009,
 248004,
 249001,
 250000,
 251001,
 252004,
 253009,
 254016,
 255025,
 256036,
 257049,
 258064,
 259081,
 260100,
 261121,
 262144,
 263169,
 264196,
 265225,
 266256,
 267289,
 268324,
 269361,
 270400,
 271441,
 272484,
 273529,
 274576,
 275625,
 276676,
 277729,
 278784,
 279841,
 280900,
 281961,
 283024,
 284089,
 285156,
 286225,
 287296,
 288369,
 289444,
 290521,
 291600,
 292681,
 293764,
 294849,
 295936,
 297025,
 298116,
 299209,
 300304,
 301401,
 302500,
 303601,
 304704,
 305809,
 306916,
 308025,
 309136,
 310249,
 311364,
 312481,
 313600,
 314721,
 315844,
 316969,
 318096,
 319225,
 320356,
 321489,
 322624,
 323761,
 324900,
 326041,
 327184,
 328329,
 329476,
 330625,
 331776,
 332929,
 334084,
 335241,
 336400,
 337561,
 338724,
 339889,
 341056,
 342225,
 343396,
 344569,
 345744,
 346921,
 348100,
 349281,
 350464,
 351649,
 352836,
 354025,
 355216,
 356409,
 357604,
 358801,
 360000,
 361201,
 362404,
 363609,
 364816,
 366025,
 367236,
 368449,
 369664,
 370881,
 372100,
 373321,
 374544,
 375769,
 376996,
 378225,
 379456,
 380689,
 381924,
 383161,
 384400,
 385641,
 386884,
 388129,
 389376,
 390625,
 391876,
 393129,
 394384,
 395641,
 396900,
 398161,
 399424,
 400689,
 401956,
 403225,
 404496,
 405769,
 407044,
 408321,
 409600,
 410881,
 412164,
 413449,
 414736,
 416025,
 417316,
 418609,
 419904,
 421201,
 422500,
 423801,
 425104,
 426409,
 427716,
 429025,
 430336,
 431649,
 432964,
 434281,
 435600,
 436921,
 438244,
 439569,
 440896,
 442225,
 443556,
 444889,
 446224,
 447561,
 448900,
 450241,
 451584,
 452929,
 454276,
 455625,
 456976,
 458329,
 459684,
 461041,
 462400,
 463761,
 465124,
 466489,
 467856,
 469225,
 470596,
 471969,
 473344,
 474721,
 476100,
 477481,
 478864,
 480249,
 481636,
 483025,
 484416,
 485809,
 487204,
 488601,
 490000,
 491401,
 492804,
 494209,
 495616,
 497025,
 498436,
 499849,
 501264,
 502681,
 504100,
 505521,
 506944,
 508369,
 509796,
 511225,
 512656,
 514089,
 515524,
 516961,
 518400,
 519841,
 521284,
 522729,
 524176,
 525625,
 527076,
 528529,
 529984,
 531441,
 532900,
 534361,
 535824,
 537289,
 538756,
 540225,
 541696,
 543169,
 544644,
 546121,
 547600,
 549081,
 550564,
 552049,
 553536,
 555025,
 556516,
 558009,
 559504,
 561001,
 562500,
 564001,
 565504,
 567009,
 568516,
 570025,
 571536,
 573049,
 574564,
 576081,
 577600,
 579121,
 580644,
 582169,
 583696,
 585225,
 586756,
 588289,
 589824,
 591361,
 592900,
 594441,
 595984,
 597529,
 599076,
 600625,
 602176,
 603729,
 605284,
 606841,
 608400,
 609961,
 611524,
 613089,
 614656,
 616225,
 617796,
 619369,
 620944,
 622521,
 624100,
 625681,
 627264,
 628849,
 630436,
 632025,
 633616,
 635209,
 636804,
 638401,
 640000,
 641601,
 643204,
 644809,
 646416,
 648025,
 649636,
 651249,
 652864,
 654481,
 656100,
 657721,
 659344,
 660969,
 662596,
 664225,
 665856,
 667489,
 669124,
 670761,
 672400,
 674041,
 675684,
 677329,
 678976,
 680625,
 682276,
 683929,
 685584,
 687241,
 688900,
 690561,
 692224,
 693889,
 695556,
 697225,
 698896,
 700569,
 702244,
 703921,
 705600,
 707281,
 708964,
 710649,
 712336,
 714025,
 715716,
 717409,
 719104,
 720801,
 722500,
 724201,
 725904,
 727609,
 729316,
 731025,
 732736,
 734449,
 736164,
 737881,
 739600,
 741321,
 743044,
 744769,
 746496,
 748225,
 749956,
 751689,
 753424,
 755161,
 756900,
 758641,
 760384,
 762129,
 763876,
 765625,
 767376,
 769129,
 770884,
 772641,
 774400,
 776161,
 777924,
 779689,
 781456,
 783225,
 784996,
 786769,
 788544,
 790321,
 792100,
 793881,
 795664,
 797449,
 799236,
 801025,
 802816,
 804609,
 806404,
 808201,
 810000,
 811801,
 813604,
 815409,
 817216,
 819025,
 820836,
 822649,
 824464,
 826281,
 828100,
 829921,
 831744,
 833569,
 835396,
 837225,
 839056,
 840889,
 842724,
 844561,
 846400,
 848241,
 850084,
 851929,
 853776,
 855625,
 857476,
 859329,
 861184,
 863041,
 864900,
 866761,
 868624,
 870489,
 872356,
 874225,
 876096,
 877969,
 879844,
 881721,
 883600,
 885481,
 887364,
 889249,
 891136,
 893025,
 894916,
 896809,
 898704,
 900601,
 902500,
 904401,
 906304,
 908209,
 910116,
 912025,
 913936,
 915849,
 917764,
 919681,
 921600,
 923521,
 925444,
 927369,
 929296,
 931225,
 933156,
 935089,
 937024,
 938961,
 940900,
 942841,
 944784,
 946729,
 948676,
 950625,
 952576,
 954529,
 956484,
 958441,
 960400,
 962361,
 964324,
 966289,
 968256,
 970225,
 972196,
 974169,
 976144,
 978121,
 980100,
 982081,
 984064,
 986049,
 988036,
 990025,
 992016,
 994009,
 996004,
 998001,
 1000000,
 ...]

In [7]:
import numpy as np

def squaringII():
    start_time = time.time()
    start = 1
    end = 21
    num_elements = 20
    x_values = np.linspace(start, end, num_elements, dtype=int, endpoint=False)
    y = x_values ** 2
    print("Total Time:",(time.time() - start_time))
    return y

squaringII()

Total Time: 0.0

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [16]:
from datetime import datetime, timedelta
def months_into_days(comm_date, start_date):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(start_date, "%m/%d/%Y")
    # date_a = datetime.strptime(comm_date, "%d/%m/%Y")
    # date_b = datetime.strptime(start_date, "%d/%m/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

In [17]:
import time
from datetime import datetime, timedelta

def calculate_policy_month(commencement_date, total_policy_months, start_date):
        start_time = time.time()
        policy_month_col = [months_into_days(commencement_date, start_date)]
        print(policy_month_col[0])
        total_iterations = total_policy_months - policy_month_col[0]
        print(total_iterations)
        for i in range(1, total_iterations):
            try:
                if((policy_month_col[i-1] + 1) < total_policy_months):
                    policy_month_col.append(policy_month_col[i-1] + 1)
                else:
                     policy_month_col.append(0)
            except ValueError:
                    policy_month_col.append(0)
        print("Total Time:",(time.time() - start_time))
        return policy_month_col

In [15]:
for i in range(1, 3):
    print(i)

1
2

In [21]:
calculate_policy_month("6/30/2021", 132, "1/1/2021")

-5
137
Total Time: 0.0012671947479248047

[-5,
 -4,
 -3,
 -2,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131]

In [4]:
import numpy as np
import time
import pandas as pd

def calculate_policy_month(commencement_date, total_policy_months, start_date):
    start_time = time.time()
    pol_month_val = months_into_days(commencement_date, start_date)
    print("Pol valu:",pol_month_val)
    total_arr_val = (total_policy_months - pol_month_val) + 1
    print("Total arr val:",total_arr_val)
    policy_month_col = np.zeros(total_arr_val, dtype=int)
#     policy_month_col = np.zeros(total_policy_months, dtype=int)
    policy_month_col[0] = pol_month_val
#     policy_month_col[0] = months_into_days(commencement_date, start_date)
#     total_iterations = total_policy_months - policy_month_col[0]
    
    if total_arr_val > 0:
        incremental_values = np.arange(1, total_arr_val)
        print("Incremental Values:",incremental_values)
        policy_month_col[1:total_arr_val] = np.minimum(
            policy_month_col[0] + incremental_values, total_policy_months)
    print("Total Time:",(time.time() - start_time))
    print(len(policy_month_col))
    table = {
        'Policy Month': policy_month_col
    }
    df = pd.DataFrame(table)
    return df

In [5]:
#calculate_policy_month("4/28/2015", 132, "1/1/2021")
calculate_policy_month("1/24/2012", 60, "1/1/2021")

Pol valu: 110
Total arr val: -49

ValueError: negative dimensions are not allowed

In [20]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [23]:
x= []
x[0:5] = np.minimum(132, 132)
x

TypeError: can only assign an iterable