In [1]:
import pandas as pd
policies = pd.read_csv("policies_input.csv", delimiter=';')
#print(policies[policies['PPR_PRODCD'] == 302])
print(policies)

    PROPOSAL_NO  POLICY_NO PREMIUM_FREQUENCY  PPR_PRODCD     PRODUCT_NAME  \
0     100092775  100092775                 A         301    Save & Assure
1     100092772  100092772                 A         301    Save & Assure
2     100092780  100092780                 A         301    Save & Assure
3     100092777  100092777                 A         301    Save & Assure
4     100092771  100092771                 A         301    Save & Assure
5     100092767  100092767                 A         301    Save & Assure
6     100069181  100069181                 M         302   Cover for Life
7     100071142  100071142                 M         302   Cover for Life
8     100068065  100068065                 M         302   Cover for Life
9     100069673  100069673                 M         302   Cover for Life
10    100043878  100043878                 M         302   Cover for Life
11    100070660  100070660                 M         302   Cover for Life
12    100084433  100084433                 M         302   Cover for Life
13    100039166  100039166                 M         302   Cover for Life
14    100089799  100089799                 M         302   Cover for Life
15    100048666  100048666                 M         302   Cover for Life
16    100068061  100068061                 M         302   Cover for Life
17    100038871  100038871                 M         302   Cover for Life
18    100050732  100050732                 S         303  Invest For Life
19    100040145  100040145                 S         303  Invest For Life
20    100050730  100050730                 S         303  Invest For Life
21    100193177  100193177                 S         303  Invest For Life
22    100039225  100039225                 S         303  Invest For Life
23    100040654  100040654                 S         303  Invest For Life
24    100026784  100026784                 S         303  Invest For Life
25    100039203  100039203                 S         303  Invest For Life
26    100037617  100037617                 S         303  Invest For Life
27    100044745  100044745                 S         303  Invest For Life
28    100199621  100199621                 S         303  Invest For Life
29    100171523  100171523                 S         303  Invest For Life
30    100064824  100064824                 H         304    Invest Assure
31    100052311  100052311                 A         304    Invest Assure
32    100037506  100037506                 A         304    Invest Assure
33    100069073  100069073                 A         304    Invest Assure
34    100030596  100030596                 A         304    Invest Assure
35    100043327  100043327                 A         304    Invest Assure
36    100069073  100069073                 A         304    Invest Assure
37    100037191  100037191                 A         304    Invest Assure
38    100044462  100044462                 M         304    Invest Assure
39    100069072  100069072                 A         304    Invest Assure
40    100079254  100079254                 A         304    Invest Assure
41    100036860  100036860                 M         304    Invest Assure
42    100036767  100036767                 Q         304    Invest Assure
43    100030604  100030604                 A         304    Invest Assure
44    100047812  100047812                 A         304    Invest Assure

   ISSUANCE_DATE COMMENCEMENT_DATE  NETPREMIUM  BASIC_SUMASSURED INSURED_SEX  \
0     26/05/2015        28/04/2015      250000            244625           M
1     31/03/2015        28/03/2015      500000            489250           M
2     25/03/2015        25/03/2015      700000            918780           M
3     27/03/2015        27/03/2015      250000            484410           M
4     27/03/2015        27/03/2015      600000             95931           M
5     19/03/2015        19/03/2015      500000           1000000           M
6     26/06/2014        17/06/2014      153000            506496           M
7     30/08/2014        28/08/2014      243000            973800           M
8     04/07/2014        04/07/2014       36448                 0           M
9     15/07/2014        28/06/2014      162000            210240           M
10    03/05/2013        28/04/2013       40000           1504152           M
11    20/08/2014        20/08/2014       72000            468437           M
12    09/04/2015        09/04/2015      109500            462379           M
13    31/01/2013        21/01/2013       94500           1902096           M
14    21/04/2015        21/04/2015      146000            340560           M
15    28/06/2013        17/06/2013      301000            803880           M
16    04/07/2014        04/07/2014      225000            498777           M
17    31/01/2013        28/01/2013       10500            329695           M
18    24/07/2013        23/07/2013     2000000           2000000           M
19    13/02/2013        12/02/2013      250000            250000           F
20    24/07/2013        23/07/2013     1000000           1000000           M
21    06/02/2017        06/02/2017      700000            875000           F
22    23/01/2013        22/01/2013     5000000           5000000           M
23    22/02/2013        22/02/2013      100000            100000           M
24    17/05/2012        16/05/2012     1000000           1000000           M
25    23/01/2013        22/01/2013     2000000           2000000           M
26    20/12/2012        20/12/2012       25000             25000           M
27    10/05/2013        24/04/2013       99000             99000           M
28    03/03/2017        03/03/2017      300000            375000           M
29    14/10/2016        14/10/2016       60000             75000           F
30    21/03/2014        21/03/2014      500000           1223120           F
31    28/08/2013        28/08/2013      175000             68316           M
32    19/12/2012        19/12/2012      510000            831720           M
33    25/06/2014        25/06/2014      500000            100000           M
34    06/08/2012        06/08/2012     1350000            440325           M
35    19/04/2013        19/04/2013       50000            250000           M
36    25/06/2014        25/06/2014      500000            100000           M
37    24/12/2012        24/12/2012       20000            140325           M
38    29/04/2013        28/04/2013      116693            500040           M
39    04/06/2014        04/06/2014       50000             75000           M
40    21/10/2014        21/10/2014      250000            148065           M
41    10/12/2012        10/12/2012       70000            867779           F
42    10/12/2012        10/12/2012      100000           1000000           M
43    30/07/2012        28/07/2012      500000            300000           F
44    31/05/2013        28/05/2013       50000            243550           M

    INSURED_DOB COVERMULTIPLE  BENEFIT_TERM BASIC_CASH_VALUE Group Code  \
0         23887             5            11      236342,1429       T-20
1         26884             5            11      490965,0832       T-20
2         26755            10            12      636415,4407       T-20
3         28714            10            11      235391,8769       T-20
4         24473             1            12      592061,0287       T-20
5         25204            10            10      441683,6827       T-20
6         26397            16            25      118615,2547       T-20
7         31615            30            25      217549,4096       T-20
8         26662             0            25      11949,40198       T-20
9         24532            10            18      139099,9577       T-20
10        26299            26            21      17480,18644       T-20
11        32035            30            25      55979,81719       T-20
12        29578            30            25      85502,50952       T-20
13        33172            28            25      52341,27273       T-20
14        25661            15            21      122613,9707       T-20
15        26365            30            25      201869,2957       T-20
16        28854            15            25      204242,4362       T-20
17        26464            25            25      3734,000215       T-20
18        29647             1            10      3515881,319       T-20
19        25934             1            10      454573,7862       T-20
20        29647             1            10      1757941,864       T-20
21        25569          1,25            10      885320,5978       T-20
22        21119             1            10      9133975,227       T-20
23        28556             1            10      181297,1001       T-20
24        30722             1            10      2030325,573       T-20
25        21119             1            10       3646662,99       T-20
26        27400             1            10      46021,34185       T-20
27        21916             1            10      133583,6074       T-20
28        26539          1,25            10      382602,1501       T-20
29        27395          1,25             5      77858,18381       T-20
30        31321             5            11      391596,9868       T-20
31        27030             3            10      174958,9773       T-20
32        20019            10            20      317720,7554       T-20
33        18379             1            10      520378,8142       T-20
34        19360             3            12      1466151,017       T-20
35        26361            10            10      40291,27504       T-20
36        18379             1            10                0       T-20
37        21916            15            15                0       T-20
38        24473            10            10      81464,40772       T-20
39        28985             3            12      40869,92538       T-20
40        28173             3            12       242637,749       T-20
41        30682            15            10      45771,99541       T-20
42        21551            20            10                0       T-20
43        25530             3            10      618107,7447       T-20
44        27744            10            25      39658,79868       T-20

               POLICY_STATUS  Status_code
0                 REINSTATED            1
1          ACTIVE  (INFORCE)            1
2          ACTIVE  (INFORCE)            1
3               AUTO PAID UP            2
4               AUTO PAID UP            2
5                 REINSTATED            1
6               AUTO PAID UP            2
7                 REINSTATED            1
8   D/C CONTINUATION BENEFIT            3
9                 REINSTATED            1
10      LAPSED - NON PAYMENT            4
11              AUTO PAID UP            2
12              AUTO PAID UP            2
13      LAPSED - NON PAYMENT            4
14              AUTO PAID UP            2
15                REINSTATED            1
16              AUTO PAID UP            2
17      LAPSED - NON PAYMENT            4
18         ACTIVE  (INFORCE)            1
19         ACTIVE  (INFORCE)            1
20         ACTIVE  (INFORCE)            1
21         ACTIVE  (INFORCE)            1
22         ACTIVE  (INFORCE)            1
23         ACTIVE  (INFORCE)            1
24         ACTIVE  (INFORCE)            1
25         ACTIVE  (INFORCE)            1
26         ACTIVE  (INFORCE)            1
27         ACTIVE  (INFORCE)            1
28         ACTIVE  (INFORCE)            1
29         ACTIVE  (INFORCE)            1
30              AUTO PAID UP            2
31              AUTO PAID UP            2
32              AUTO PAID UP            2
33         ACTIVE  (INFORCE)            1
34                REINSTATED            1
35              AUTO PAID UP            2
36         ACTIVE  (INFORCE)            1
37              AUTO PAID UP            2
38              AUTO PAID UP            2
39              AUTO PAID UP            2
40              AUTO PAID UP            2
41      LAPSED - NON PAYMENT            4
42              AUTO PAID UP            2
43         ACTIVE  (INFORCE)            1
44              AUTO PAID UP            2

In [2]:
products_in_data = policies['PPR_PRODCD'].unique()
print(products_in_data)

[301 302 303 304]

In [3]:
import json

def read_json(path):
   # print("Reading json")
    with open(path, 'r') as f:
            json_content = json.loads(f.read())
    
    return json_content

In [4]:
products = read_json("products.json")
print(products)

{'products': {'301': {'gender': '', 'admin_inflation': 0.0, 'bid_offer': 5.0, 'admin_charges_annual': 0, 'imc_annual': 1.6, 'growth_rate': 0.64, 'surrendered_charges': 350, 'benefit_type': 2, 'fixed_expenses': {'first_year': 0, 'second_year': 0, 'inflation_rate': 0.0, 'renewal_expense_premium': 0.0, 'aquisition_expense': 0, 'admin_expense': 0, 'expected_actual_mortality_charge': 100.0, 'mortality_charge_loading': 125.0}, 'assumptions': {'allocation': 'data/assumptions/301/allocation.csv', 'lapse_rate': 'data/assumptions/301/lapse_rate.csv', 'commission': 'data/assumptions/301/comission.csv', 'persistency': 'data/assumptions/301/persistency.csv', 'surrender': 'data/assumptions/301/surrender.csv'}}, '302': {'gender': '', 'admin_inflation': 0.0, 'bid_offer': 5.0, 'admin_charges_annual': 0, 'imc_annual': 1.6, 'growth_rate': 0.64, 'surrendered_charges': 350, 'benefit_type': 2, 'fixed_expenses': {'first_year': 0, 'second_year': 0, 'inflation_rate': 0.0, 'renewal_expense_premium': 0.0, 'aquisition_expense': 0, 'admin_expense': 0, 'expected_actual_mortality_charge': 100.0, 'mortality_charge_loading': 125.0}, 'assumptions': {'allocation': 'data/assumptions/302/allocation.csv', 'lapse_rate': 'data/assumptions/302/lapse_rate.csv', 'commission': 'data/assumptions/302/comission.csv', 'persistency': 'data/assumptions/302/persistency.csv', 'surrender': 'data/assumptions/302/surrender.csv'}}, '303': {'gender': '', 'admin_inflation': 0.0, 'bid_offer': 5.0, 'admin_charges_annual': 0, 'imc_annual': 1.6, 'growth_rate': 0.64, 'surrendered_charges': 350, 'benefit_type': 2, 'fixed_expenses': {'first_year': 0, 'second_year': 0, 'inflation_rate': 0.0, 'renewal_expense_premium': 0.0, 'aquisition_expense': 0, 'admin_expense': 0, 'expected_actual_mortality_charge': 100.0, 'mortality_charge_loading': 125.0}, 'assumptions': {'allocation': 'data/assumptions/303/allocation.csv', 'lapse_rate': 'data/assumptions/303/lapse_rate.csv', 'commission': 'data/assumptions/303/comission.csv', 'persistency': 'data/assumptions/303/persistency.csv', 'surrender': 'data/assumptions/303/surrender.csv'}}, '304': {'gender': '', 'admin_inflation': 0.0, 'bid_offer': 5.0, 'admin_charges_annual': 0, 'imc_annual': 1.6, 'growth_rate': 0.64, 'surrendered_charges': 350, 'benefit_type': 2, 'fixed_expenses': {'first_year': 0, 'second_year': 0, 'inflation_rate': 0.0, 'renewal_expense_premium': 0.0, 'aquisition_expense': 0, 'admin_expense': 0, 'expected_actual_mortality_charge': 100.0, 'mortality_charge_loading': 125.0}, 'assumptions': {'allocation': 'data/assumptions/304/allocation.csv', 'lapse_rate': 'data/assumptions/304/lapse_rate.csv', 'commission': 'data/assumptions/304/comission.csv', 'persistency': 'data/assumptions/304/persistency.csv', 'surrender': 'data/assumptions/304/surrender.csv'}}}}

In [5]:
def read_csv_to_array(filepath):
    return pd.read_csv(filepath, header=None).squeeze().tolist()

In [6]:
#convert csv data into array
data = pd.read_csv("data/assumptions/301/allocation.csv", header=None).squeeze().tolist()
print(data)

[1.0, 0.1, 0.1, 0.1, 0.01, 0.01, 0.1, 0.1, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [7]:
def load_assumptions_data(product_assumptions):
    #print("product:",product_assumptions)
    allocation = read_csv_to_array(product_assumptions['allocation'])
    lapse_rate = read_csv_to_array(product_assumptions['lapse_rate'])
    commission = read_csv_to_array(product_assumptions['commission'])
    persistency = read_csv_to_array(product_assumptions['persistency'])
    surrender = read_csv_to_array(product_assumptions['surrender'])

    return allocation, lapse_rate, commission, persistency, surrender

In [8]:
import sys

for key in products_in_data:
    try:
       #loading assumptions for the current product from loaded json
        product_info = products['products'][str(key)]
        allocation, lapse_rate, commission, persistency, surrender = load_assumptions_data(product_info['assumptions'])
        #print("Lapse Rate:",lapse_rate)
      #  print("ALLOCATION:",allocation)
       # print("SURRENDER:",surrender)
    except Exception as e:
        print(f"Product assumptions are not available in the provided file: {e}")
        sys.exit()
        
    policies_subset = policies[policies['PPR_PRODCD'] == key]
    print(policies_subset)
    
    for index, row in policies_subset.iterrows():
        print("INDEX:",index)
        print("ROW:",row)

Lapse Rate: [0.15, 0.12, 0.1, 0.1, 0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]
   PROPOSAL_NO  POLICY_NO PREMIUM_FREQUENCY  PPR_PRODCD   PRODUCT_NAME  \
0    100092775  100092775                 A         301  Save & Assure
1    100092772  100092772                 A         301  Save & Assure
2    100092780  100092780                 A         301  Save & Assure
3    100092777  100092777                 A         301  Save & Assure
4    100092771  100092771                 A         301  Save & Assure
5    100092767  100092767                 A         301  Save & Assure

  ISSUANCE_DATE COMMENCEMENT_DATE  NETPREMIUM  BASIC_SUMASSURED INSURED_SEX  \
0    26/05/2015        28/04/2015      250000            244625           M
1    31/03/2015        28/03/2015      500000            489250           M
2    25/03/2015        25/03/2015      700000            918780           M
3    27/03/2015        27/03/2015      250000            484410           M
4    27/03/2015        27/03/2015      600000             95931           M
5    19/03/2015        19/03/2015      500000           1000000           M

   INSURED_DOB COVERMULTIPLE  BENEFIT_TERM BASIC_CASH_VALUE Group Code  \
0        23887             5            11      236342,1429       T-20
1        26884             5            11      490965,0832       T-20
2        26755            10            12      636415,4407       T-20
3        28714            10            11      235391,8769       T-20
4        24473             1            12      592061,0287       T-20
5        25204            10            10      441683,6827       T-20

       POLICY_STATUS  Status_code
0         REINSTATED            1
1  ACTIVE  (INFORCE)            1
2  ACTIVE  (INFORCE)            1
3       AUTO PAID UP            2
4       AUTO PAID UP            2
5         REINSTATED            1
INDEX: 0
ROW: PROPOSAL_NO              100092775
POLICY_NO                100092775
PREMIUM_FREQUENCY                A
PPR_PRODCD                     301
PRODUCT_NAME         Save & Assure
ISSUANCE_DATE           26/05/2015
COMMENCEMENT_DATE       28/04/2015
NETPREMIUM                  250000
BASIC_SUMASSURED            244625
INSURED_SEX                      M
INSURED_DOB                  23887
COVERMULTIPLE                    5
BENEFIT_TERM                    11
BASIC_CASH_VALUE       236342,1429
Group Code                    T-20
POLICY_STATUS           REINSTATED
Status_code                      1
Name: 0, dtype: object
INDEX: 1
ROW: PROPOSAL_NO                  100092772
POLICY_NO                    100092772
PREMIUM_FREQUENCY                    A
PPR_PRODCD                         301
PRODUCT_NAME             Save & Assure
ISSUANCE_DATE               31/03/2015
COMMENCEMENT_DATE           28/03/2015
NETPREMIUM                      500000
BASIC_SUMASSURED                489250
INSURED_SEX                          M
INSURED_DOB                      26884
COVERMULTIPLE                        5
BENEFIT_TERM                        11
BASIC_CASH_VALUE           490965,0832
Group Code                        T-20
POLICY_STATUS        ACTIVE  (INFORCE)
Status_code                          1
Name: 1, dtype: object
INDEX: 2
ROW: PROPOSAL_NO                  100092780
POLICY_NO                    100092780
PREMIUM_FREQUENCY                    A
PPR_PRODCD                         301
PRODUCT_NAME             Save & Assure
ISSUANCE_DATE               25/03/2015
COMMENCEMENT_DATE           25/03/2015
NETPREMIUM                      700000
BASIC_SUMASSURED                918780
INSURED_SEX                          M
INSURED_DOB                      26755
COVERMULTIPLE                       10
BENEFIT_TERM                        12
BASIC_CASH_VALUE           636415,4407
Group Code                        T-20
POLICY_STATUS        ACTIVE  (INFORCE)
Status_code                          1
Name: 2, dtype: object
INDEX: 3
ROW: PROPOSAL_NO              100092777
POLICY_NO                100092777
PREMIUM_FREQUENCY                A
PPR_PRODCD                     301
PRODUCT_NAME         Save & Assure
ISSUANCE_DATE           27/03/2015
COMMENCEMENT_DATE       27/03/2015
NETPREMIUM                  250000
BASIC_SUMASSURED            484410
INSURED_SEX                      M
INSURED_DOB                  28714
COVERMULTIPLE                   10
BENEFIT_TERM                    11
BASIC_CASH_VALUE       235391,8769
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 3, dtype: object
INDEX: 4
ROW: PROPOSAL_NO              100092771
POLICY_NO                100092771
PREMIUM_FREQUENCY                A
PPR_PRODCD                     301
PRODUCT_NAME         Save & Assure
ISSUANCE_DATE           27/03/2015
COMMENCEMENT_DATE       27/03/2015
NETPREMIUM                  600000
BASIC_SUMASSURED             95931
INSURED_SEX                      M
INSURED_DOB                  24473
COVERMULTIPLE                    1
BENEFIT_TERM                    12
BASIC_CASH_VALUE       592061,0287
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 4, dtype: object
INDEX: 5
ROW: PROPOSAL_NO              100092767
POLICY_NO                100092767
PREMIUM_FREQUENCY                A
PPR_PRODCD                     301
PRODUCT_NAME         Save & Assure
ISSUANCE_DATE           19/03/2015
COMMENCEMENT_DATE       19/03/2015
NETPREMIUM                  500000
BASIC_SUMASSURED           1000000
INSURED_SEX                      M
INSURED_DOB                  25204
COVERMULTIPLE                   10
BENEFIT_TERM                    10
BASIC_CASH_VALUE       441683,6827
Group Code                    T-20
POLICY_STATUS           REINSTATED
Status_code                      1
Name: 5, dtype: object
Lapse Rate: [0.15, 0.12, 0.1, 0.1, 0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]
    PROPOSAL_NO  POLICY_NO PREMIUM_FREQUENCY  PPR_PRODCD    PRODUCT_NAME  \
6     100069181  100069181                 M         302  Cover for Life
7     100071142  100071142                 M         302  Cover for Life
8     100068065  100068065                 M         302  Cover for Life
9     100069673  100069673                 M         302  Cover for Life
10    100043878  100043878                 M         302  Cover for Life
11    100070660  100070660                 M         302  Cover for Life
12    100084433  100084433                 M         302  Cover for Life
13    100039166  100039166                 M         302  Cover for Life
14    100089799  100089799                 M         302  Cover for Life
15    100048666  100048666                 M         302  Cover for Life
16    100068061  100068061                 M         302  Cover for Life
17    100038871  100038871                 M         302  Cover for Life

   ISSUANCE_DATE COMMENCEMENT_DATE  NETPREMIUM  BASIC_SUMASSURED INSURED_SEX  \
6     26/06/2014        17/06/2014      153000            506496           M
7     30/08/2014        28/08/2014      243000            973800           M
8     04/07/2014        04/07/2014       36448                 0           M
9     15/07/2014        28/06/2014      162000            210240           M
10    03/05/2013        28/04/2013       40000           1504152           M
11    20/08/2014        20/08/2014       72000            468437           M
12    09/04/2015        09/04/2015      109500            462379           M
13    31/01/2013        21/01/2013       94500           1902096           M
14    21/04/2015        21/04/2015      146000            340560           M
15    28/06/2013        17/06/2013      301000            803880           M
16    04/07/2014        04/07/2014      225000            498777           M
17    31/01/2013        28/01/2013       10500            329695           M

    INSURED_DOB COVERMULTIPLE  BENEFIT_TERM BASIC_CASH_VALUE Group Code  \
6         26397            16            25      118615,2547       T-20
7         31615            30            25      217549,4096       T-20
8         26662             0            25      11949,40198       T-20
9         24532            10            18      139099,9577       T-20
10        26299            26            21      17480,18644       T-20
11        32035            30            25      55979,81719       T-20
12        29578            30            25      85502,50952       T-20
13        33172            28            25      52341,27273       T-20
14        25661            15            21      122613,9707       T-20
15        26365            30            25      201869,2957       T-20
16        28854            15            25      204242,4362       T-20
17        26464            25            25      3734,000215       T-20

               POLICY_STATUS  Status_code
6               AUTO PAID UP            2
7                 REINSTATED            1
8   D/C CONTINUATION BENEFIT            3
9                 REINSTATED            1
10      LAPSED - NON PAYMENT            4
11              AUTO PAID UP            2
12              AUTO PAID UP            2
13      LAPSED - NON PAYMENT            4
14              AUTO PAID UP            2
15                REINSTATED            1
16              AUTO PAID UP            2
17      LAPSED - NON PAYMENT            4
INDEX: 6
ROW: PROPOSAL_NO               100069181
POLICY_NO                 100069181
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            26/06/2014
COMMENCEMENT_DATE        17/06/2014
NETPREMIUM                   153000
BASIC_SUMASSURED             506496
INSURED_SEX                       M
INSURED_DOB                   26397
COVERMULTIPLE                    16
BENEFIT_TERM                     25
BASIC_CASH_VALUE        118615,2547
Group Code                     T-20
POLICY_STATUS          AUTO PAID UP
Status_code                       2
Name: 6, dtype: object
INDEX: 7
ROW: PROPOSAL_NO               100071142
POLICY_NO                 100071142
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            30/08/2014
COMMENCEMENT_DATE        28/08/2014
NETPREMIUM                   243000
BASIC_SUMASSURED             973800
INSURED_SEX                       M
INSURED_DOB                   31615
COVERMULTIPLE                    30
BENEFIT_TERM                     25
BASIC_CASH_VALUE        217549,4096
Group Code                     T-20
POLICY_STATUS            REINSTATED
Status_code                       1
Name: 7, dtype: object
INDEX: 8
ROW: PROPOSAL_NO                         100068065
POLICY_NO                           100068065
PREMIUM_FREQUENCY                           M
PPR_PRODCD                                302
PRODUCT_NAME                   Cover for Life
ISSUANCE_DATE                      04/07/2014
COMMENCEMENT_DATE                  04/07/2014
NETPREMIUM                              36448
BASIC_SUMASSURED                            0
INSURED_SEX                                 M
INSURED_DOB                             26662
COVERMULTIPLE                               0
BENEFIT_TERM                               25
BASIC_CASH_VALUE                  11949,40198
Group Code                               T-20
POLICY_STATUS        D/C CONTINUATION BENEFIT
Status_code                                 3
Name: 8, dtype: object
INDEX: 9
ROW: PROPOSAL_NO               100069673
POLICY_NO                 100069673
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            15/07/2014
COMMENCEMENT_DATE        28/06/2014
NETPREMIUM                   162000
BASIC_SUMASSURED             210240
INSURED_SEX                       M
INSURED_DOB                   24532
COVERMULTIPLE                    10
BENEFIT_TERM                     18
BASIC_CASH_VALUE        139099,9577
Group Code                     T-20
POLICY_STATUS            REINSTATED
Status_code                       1
Name: 9, dtype: object
INDEX: 10
ROW: PROPOSAL_NO                     100043878
POLICY_NO                       100043878
PREMIUM_FREQUENCY                       M
PPR_PRODCD                            302
PRODUCT_NAME               Cover for Life
ISSUANCE_DATE                  03/05/2013
COMMENCEMENT_DATE              28/04/2013
NETPREMIUM                          40000
BASIC_SUMASSURED                  1504152
INSURED_SEX                             M
INSURED_DOB                         26299
COVERMULTIPLE                          26
BENEFIT_TERM                           21
BASIC_CASH_VALUE              17480,18644
Group Code                           T-20
POLICY_STATUS        LAPSED - NON PAYMENT
Status_code                             4
Name: 10, dtype: object
INDEX: 11
ROW: PROPOSAL_NO               100070660
POLICY_NO                 100070660
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            20/08/2014
COMMENCEMENT_DATE        20/08/2014
NETPREMIUM                    72000
BASIC_SUMASSURED             468437
INSURED_SEX                       M
INSURED_DOB                   32035
COVERMULTIPLE                    30
BENEFIT_TERM                     25
BASIC_CASH_VALUE        55979,81719
Group Code                     T-20
POLICY_STATUS          AUTO PAID UP
Status_code                       2
Name: 11, dtype: object
INDEX: 12
ROW: PROPOSAL_NO               100084433
POLICY_NO                 100084433
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            09/04/2015
COMMENCEMENT_DATE        09/04/2015
NETPREMIUM                   109500
BASIC_SUMASSURED             462379
INSURED_SEX                       M
INSURED_DOB                   29578
COVERMULTIPLE                    30
BENEFIT_TERM                     25
BASIC_CASH_VALUE        85502,50952
Group Code                     T-20
POLICY_STATUS          AUTO PAID UP
Status_code                       2
Name: 12, dtype: object
INDEX: 13
ROW: PROPOSAL_NO                     100039166
POLICY_NO                       100039166
PREMIUM_FREQUENCY                       M
PPR_PRODCD                            302
PRODUCT_NAME               Cover for Life
ISSUANCE_DATE                  31/01/2013
COMMENCEMENT_DATE              21/01/2013
NETPREMIUM                          94500
BASIC_SUMASSURED                  1902096
INSURED_SEX                             M
INSURED_DOB                         33172
COVERMULTIPLE                          28
BENEFIT_TERM                           25
BASIC_CASH_VALUE              52341,27273
Group Code                           T-20
POLICY_STATUS        LAPSED - NON PAYMENT
Status_code                             4
Name: 13, dtype: object
INDEX: 14
ROW: PROPOSAL_NO               100089799
POLICY_NO                 100089799
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            21/04/2015
COMMENCEMENT_DATE        21/04/2015
NETPREMIUM                   146000
BASIC_SUMASSURED             340560
INSURED_SEX                       M
INSURED_DOB                   25661
COVERMULTIPLE                    15
BENEFIT_TERM                     21
BASIC_CASH_VALUE        122613,9707
Group Code                     T-20
POLICY_STATUS          AUTO PAID UP
Status_code                       2
Name: 14, dtype: object
INDEX: 15
ROW: PROPOSAL_NO               100048666
POLICY_NO                 100048666
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            28/06/2013
COMMENCEMENT_DATE        17/06/2013
NETPREMIUM                   301000
BASIC_SUMASSURED             803880
INSURED_SEX                       M
INSURED_DOB                   26365
COVERMULTIPLE                    30
BENEFIT_TERM                     25
BASIC_CASH_VALUE        201869,2957
Group Code                     T-20
POLICY_STATUS            REINSTATED
Status_code                       1
Name: 15, dtype: object
INDEX: 16
ROW: PROPOSAL_NO               100068061
POLICY_NO                 100068061
PREMIUM_FREQUENCY                 M
PPR_PRODCD                      302
PRODUCT_NAME         Cover for Life
ISSUANCE_DATE            04/07/2014
COMMENCEMENT_DATE        04/07/2014
NETPREMIUM                   225000
BASIC_SUMASSURED             498777
INSURED_SEX                       M
INSURED_DOB                   28854
COVERMULTIPLE                    15
BENEFIT_TERM                     25
BASIC_CASH_VALUE        204242,4362
Group Code                     T-20
POLICY_STATUS          AUTO PAID UP
Status_code                       2
Name: 16, dtype: object
INDEX: 17
ROW: PROPOSAL_NO                     100038871
POLICY_NO                       100038871
PREMIUM_FREQUENCY                       M
PPR_PRODCD                            302
PRODUCT_NAME               Cover for Life
ISSUANCE_DATE                  31/01/2013
COMMENCEMENT_DATE              28/01/2013
NETPREMIUM                          10500
BASIC_SUMASSURED                   329695
INSURED_SEX                             M
INSURED_DOB                         26464
COVERMULTIPLE                          25
BENEFIT_TERM                           25
BASIC_CASH_VALUE              3734,000215
Group Code                           T-20
POLICY_STATUS        LAPSED - NON PAYMENT
Status_code                             4
Name: 17, dtype: object
Lapse Rate: [0.15, 0.12, 0.1, 0.1, 0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]
    PROPOSAL_NO  POLICY_NO PREMIUM_FREQUENCY  PPR_PRODCD     PRODUCT_NAME  \
18    100050732  100050732                 S         303  Invest For Life
19    100040145  100040145                 S         303  Invest For Life
20    100050730  100050730                 S         303  Invest For Life
21    100193177  100193177                 S         303  Invest For Life
22    100039225  100039225                 S         303  Invest For Life
23    100040654  100040654                 S         303  Invest For Life
24    100026784  100026784                 S         303  Invest For Life
25    100039203  100039203                 S         303  Invest For Life
26    100037617  100037617                 S         303  Invest For Life
27    100044745  100044745                 S         303  Invest For Life
28    100199621  100199621                 S         303  Invest For Life
29    100171523  100171523                 S         303  Invest For Life

   ISSUANCE_DATE COMMENCEMENT_DATE  NETPREMIUM  BASIC_SUMASSURED INSURED_SEX  \
18    24/07/2013        23/07/2013     2000000           2000000           M
19    13/02/2013        12/02/2013      250000            250000           F
20    24/07/2013        23/07/2013     1000000           1000000           M
21    06/02/2017        06/02/2017      700000            875000           F
22    23/01/2013        22/01/2013     5000000           5000000           M
23    22/02/2013        22/02/2013      100000            100000           M
24    17/05/2012        16/05/2012     1000000           1000000           M
25    23/01/2013        22/01/2013     2000000           2000000           M

ROW: PROPOSAL_NO              100044462
POLICY_NO                100044462
PREMIUM_FREQUENCY                M
PPR_PRODCD                     304
PRODUCT_NAME         Invest Assure
ISSUANCE_DATE           29/04/2013
COMMENCEMENT_DATE       28/04/2013
NETPREMIUM                  116693
BASIC_SUMASSURED            500040
INSURED_SEX                      M
INSURED_DOB                  24473
COVERMULTIPLE                   10
BENEFIT_TERM                    10
BASIC_CASH_VALUE       81464,40772
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 38, dtype: object
INDEX: 39
ROW: PROPOSAL_NO              100069072
POLICY_NO                100069072
PREMIUM_FREQUENCY                A
PPR_PRODCD                     304
PRODUCT_NAME         Invest Assure
ISSUANCE_DATE           04/06/2014
COMMENCEMENT_DATE       04/06/2014
NETPREMIUM                   50000
BASIC_SUMASSURED             75000
INSURED_SEX                      M
INSURED_DOB                  28985
COVERMULTIPLE                    3
BENEFIT_TERM                    12
BASIC_CASH_VALUE       40869,92538
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 39, dtype: object
INDEX: 40
ROW: PROPOSAL_NO              100079254
POLICY_NO                100079254
PREMIUM_FREQUENCY                A
PPR_PRODCD                     304
PRODUCT_NAME         Invest Assure
ISSUANCE_DATE           21/10/2014
COMMENCEMENT_DATE       21/10/2014
NETPREMIUM                  250000
BASIC_SUMASSURED            148065
INSURED_SEX                      M
INSURED_DOB                  28173
COVERMULTIPLE                    3
BENEFIT_TERM                    12
BASIC_CASH_VALUE        242637,749
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 40, dtype: object
INDEX: 41
ROW: PROPOSAL_NO                     100036860
POLICY_NO                       100036860
PREMIUM_FREQUENCY                       M
PPR_PRODCD                            304
PRODUCT_NAME                Invest Assure
ISSUANCE_DATE                  10/12/2012
COMMENCEMENT_DATE              10/12/2012
NETPREMIUM                          70000
BASIC_SUMASSURED                   867779
INSURED_SEX                             F
INSURED_DOB                         30682
COVERMULTIPLE                          15
BENEFIT_TERM                           10
BASIC_CASH_VALUE              45771,99541
Group Code                           T-20
POLICY_STATUS        LAPSED - NON PAYMENT
Status_code                             4
Name: 41, dtype: object
INDEX: 42
ROW: PROPOSAL_NO              100036767
POLICY_NO                100036767
PREMIUM_FREQUENCY                Q
PPR_PRODCD                     304
PRODUCT_NAME         Invest Assure
ISSUANCE_DATE           10/12/2012
COMMENCEMENT_DATE       10/12/2012
NETPREMIUM                  100000
BASIC_SUMASSURED           1000000
INSURED_SEX                      M
INSURED_DOB                  21551
COVERMULTIPLE                   20
BENEFIT_TERM                    10
BASIC_CASH_VALUE                 0
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 42, dtype: object
INDEX: 43
ROW: PROPOSAL_NO                  100030604
POLICY_NO                    100030604
PREMIUM_FREQUENCY                    A
PPR_PRODCD                         304
PRODUCT_NAME             Invest Assure
ISSUANCE_DATE               30/07/2012
COMMENCEMENT_DATE           28/07/2012
NETPREMIUM                      500000
BASIC_SUMASSURED                300000
INSURED_SEX                          F
INSURED_DOB                      25530
COVERMULTIPLE                        3
BENEFIT_TERM                        10
BASIC_CASH_VALUE           618107,7447
Group Code                        T-20
POLICY_STATUS        ACTIVE  (INFORCE)
Status_code                          1
Name: 43, dtype: object
INDEX: 44
ROW: PROPOSAL_NO              100047812
POLICY_NO                100047812
PREMIUM_FREQUENCY                A
PPR_PRODCD                     304
PRODUCT_NAME         Invest Assure
ISSUANCE_DATE           31/05/2013
COMMENCEMENT_DATE       28/05/2013
NETPREMIUM                   50000
BASIC_SUMASSURED            243550
INSURED_SEX                      M
INSURED_DOB                  27744
COVERMULTIPLE                   10
BENEFIT_TERM                    25
BASIC_CASH_VALUE       39658,79868
Group Code                    T-20
POLICY_STATUS         AUTO PAID UP
Status_code                      2
Name: 44, dtype: object

In [9]:
from datetime import datetime, timedelta

def months_into_days(comm_date, cal_date):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(cal_month, "%m/%d/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

comm_date = "4/28/2015"
cal_month = "1/1/2021"
check = datetime.strptime(comm_date, "%m/%d/%Y")
checkB = datetime.strptime(cal_month, "%m/%d/%Y")

diff_n_days = (checkB - check).days

print(round(diff_n_days/30) + 1)

#print(((checkB - check).days)+1)/30)))

# result = ((checkB - check)+1)/30
# print(result)

70

In [10]:
months_into_days("4/28/2015", "1/1/2021")

70

In [11]:
date = "31/12/2020"
convert_in_dateObj = datetime.strptime(date, "%d/%m/%Y")
increment_month = convert_in_dateObj + timedelta(days=30)
increment_month

datetime.datetime(2021, 1, 30, 0, 0)

In [12]:
from dateutil.relativedelta import relativedelta

date = "01/05/2020"
convert_in_dateObj = datetime.strptime(date, "%d/%m/%Y")
increment_month = convert_in_dateObj + relativedelta(months=1)

print(increment_month.strftime('%d/%m/%Y'))

01/06/2020

In [13]:
from datetime import datetime, timedelta

def find_next_date(user_provided_date):
    # Convert the user-provided date to a datetime object
    input_date = datetime.strptime(user_provided_date, '%d/%m/%Y')

    # Calculate the next date
    next_date = input_date + timedelta(days=1)

    return next_date.strftime('%d/%m/%Y')

# Example usage
#user_date = '2022-01-15'
user_date = "30/11/2020"
next_date = find_next_date(user_date)

print(f"The next date after {user_date} is {next_date}")

The next date after 30/11/2020 is 01/12/2020

In [14]:
def find_same_date_next_month(input_date):
    #date = "01/05/2020"
    convert_in_dateObj = datetime.strptime(input_date, "%d/%m/%Y")
    increment_month = convert_in_dateObj + relativedelta(months=1)
    return increment_month.strftime('%d/%m/%Y')

find_same_date_next_month("02/04/2022")

'02/05/2022'

## Finding Month Calendar Month Column

In [15]:
def find_next_date(user_provided_date):
    input_date = datetime.strptime(user_provided_date, '%d/%m/%Y')
    next_date = input_date + timedelta(days=1)
    return next_date.strftime('%d/%m/%Y')

find_next_date("31/12/2020")

'01/01/2021'

In [16]:
def months_into_days(comm_date):
    date_a = datetime.strptime(comm_date, "%d/%m/%Y")
    date_b = datetime.strptime(find_next_date("31/12/2020"), "%d/%m/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

months_into_days("28/04/2015")

70

In [17]:
def find_same_date_next_month(input_date):
    convert_in_dateObj = datetime.strptime(input_date, "%d/%m/%Y")
    increment_month = convert_in_dateObj + relativedelta(months=1)
    return increment_month.strftime('%d/%m/%Y')

In [18]:
def calendar_month_column(total_policy_months):
    calendar_month = [find_next_date("31/12/2020")]
    start_month_count = months_into_days("28/04/2015")
    #print(total_policy_months - start_month_count)
    for i in range(1, (total_policy_months - start_month_count)):
        value = find_same_date_next_month(calendar_month[i - 1])
        calendar_month.append(value)
        
    return calendar_month
        
calendar_month_column(132)

['01/01/2021',
 '01/02/2021',
 '01/03/2021',
 '01/04/2021',
 '01/05/2021',
 '01/06/2021',
 '01/07/2021',
 '01/08/2021',
 '01/09/2021',
 '01/10/2021',
 '01/11/2021',
 '01/12/2021',
 '01/01/2022',
 '01/02/2022',
 '01/03/2022',
 '01/04/2022',
 '01/05/2022',
 '01/06/2022',
 '01/07/2022',
 '01/08/2022',
 '01/09/2022',
 '01/10/2022',
 '01/11/2022',
 '01/12/2022',
 '01/01/2023',
 '01/02/2023',
 '01/03/2023',
 '01/04/2023',
 '01/05/2023',
 '01/06/2023',
 '01/07/2023',
 '01/08/2023',
 '01/09/2023',
 '01/10/2023',
 '01/11/2023',
 '01/12/2023',
 '01/01/2024',
 '01/02/2024',
 '01/03/2024',
 '01/04/2024',
 '01/05/2024',
 '01/06/2024',
 '01/07/2024',
 '01/08/2024',
 '01/09/2024',
 '01/10/2024',
 '01/11/2024',
 '01/12/2024',
 '01/01/2025',
 '01/02/2025',
 '01/03/2025',
 '01/04/2025',
 '01/05/2025',
 '01/06/2025',
 '01/07/2025',
 '01/08/2025',
 '01/09/2025',
 '01/10/2025',
 '01/11/2025',
 '01/12/2025',
 '01/01/2026',
 '01/02/2026']

### Find Ploicy Month Column

In [19]:
from datetime import datetime, timedelta

In [20]:
def find_next_date(user_provided_date):
    input_date = datetime.strptime(user_provided_date, '%d/%m/%Y')
    next_date = input_date + timedelta(days=1)
    return next_date.strftime('%d/%m/%Y')

#find_next_date("31/12/2020")

In [21]:
def months_into_days(comm_date, start_date):
    date_a = datetime.strptime(comm_date, "%d/%m/%Y")
    date_b = datetime.strptime(find_next_date(start_date), "%d/%m/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

#months_into_days("28/04/2015")

In [22]:
def policy_month(commencement_date, total_policy_months, start_date):
    policy_month_col = [months_into_days(commencement_date, start_date)]
    #policy_month_col[0] = months_into_days(commencement_date, start_date)
    #start_month_count = months_into_days(commencement_date, total_policy_months)
    total_iterations = total_policy_months - policy_month_col[0]
    for i in range(1, total_iterations):
        #print(i)
        if (policy_month_col[i-1] + 1) < total_policy_months:
            policy_month_col.append(policy_month_col[i-1] + 1)
    return policy_month_col

In [23]:
pol_month_col = policy_month("28/04/2015", 132, "31/12/2020")
#pol_month_col

### Calculating Policy Year

In [24]:
def cal_policy_year_value(month):
    try:
        result = int(month / 12) + 1
    except ZeroDivisionError:
        result = 0
    return result

In [25]:
def policy_year():
    policy_month_val = policy_month("28/04/2015", 132, "31/12/2020")
    policy_year_col = []
    #print()
    for i in range(len(policy_month_val)):
        policy_year_col.append(cal_policy_year_value(policy_month_val[i]))    
    return policy_year_col

In [26]:
pol_year_col = policy_year()
#pol_year_col

### Calculating Age column

In [27]:
def age_col(age):
    age_column = []
    for i in range(len(pol_month_col)):
        if pol_month_col[i] > 0:
            age_val = (age + pol_year_col[i]) - 1
            age_column.append(age_val)
    return age_column

In [28]:
age_column = age_col(50)
#age_column

### Calculating Mortality Rate Column

In [29]:
import pandas as pd
def mortality_col():
    mortality_rates = pd.read_csv("data/rates/mortality_rates.csv", header=None).squeeze().tolist()
    Px = []
    for x in range(len(mortality_rates)-1):
        Px.append(round(mortality_rates[x+1] / mortality_rates[x], 7))
    return Px

In [30]:
mortality_column = mortality_col()
#mortality_column

### CALCULATING LAPSE RATE

In [31]:
import pandas as pd

def calculate_lapse_rate(policy_year):
    lapse_rates = pd.read_csv("data/assumptions/301/lapse_rate.csv", header=None).squeeze().tolist()
    lapse_rate_list = []
    for i in range(len(policy_year)):
        year = policy_year[i]
        lapse_value = round(((lapse_rates[year - 1]) / 12), 6)
        lapse_rate_list.append(lapse_value)
    return lapse_rate_list

In [32]:
lapse_rate = calculate_lapse_rate(pol_year_col)
lapse_rate

[0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667,
 0.006667]

### CALCULATING MORTALITY RATE

In [33]:
def calculate_mortality_rate(age):
    mortality_rates = pd.read_csv("data/rates/mortality_values.csv", header=None).squeeze().tolist()
    mortality_list = []
    for i in range(len(age)):
        age_value = age[i]
        value = mortality_rates[age_value]
        mortality_list.append(value)
    return mortality_list

In [34]:
mortality_rate = calculate_mortality_rate(age_column)
#mortality_rate

### CALCULATING INFORCE AT BEGINNING AND INFORCE AT END COLUMNS

In [35]:
def results(mortality_rate, lapse_rate, policy_month, total_policy_month):
    inforce_beginning = [1.0000]
    inforce_end = []
    for i in range(len(mortality_rate)):
        try:
            value = round(inforce_beginning[i] * (1 - mortality_rate[i] - lapse_rate[i]), 4)
            print(value)
            inforce_end.append(value)
        except Exception as e:
            val = 0
            inforce_end.append(val)
    for i in range(1, len(mortality_rate)):
        if (policy_month[i] > total_policy_month):
            inforce_beginning.append(0)
        else:
            inforce_beginning.append(inforce_end[i-1])
    return inforce_beginning, inforce_end
     
results(mortality_rate, lapse_rate, pol_month_col, 132)

0.9925

([1.0,
  0.9925,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0.9925,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0])

In [89]:
def results(mortality_rate, lapse_rate, policy_month, total_policy_month):
    inforce_beginning = [1.0000]
    inforce_end = []
    inforce_end.append(round(inforce_beginning[0] * (1 - mortality_rate[0] - lapse_rate[0]), 4))
    for i in range(1, len(mortality_rate)):
        if(policy_month[i] > total_policy_month):
            inforce_beginning.append(0)
        else:
            inforce_beginning.append(inforce_end[i-1])
        try:
            value = round(inforce_beginning[i] * (1 - mortality_rate[i] - lapse_rate[i]), 4)
            inforce_end.append(value)
        except Exception as e:
            value = 0
            inforce_end.append(value)
    return inforce_beginning, inforce_end
     
#results(mortality_rate, lapse_rate, pol_month_col, 132)[1]

## Working on Policy Account Table

### Base Premium Column

#### For first value of base premium column

In [37]:
def base_premium_first_val(start_policy_month_value, t_pol_month, prem_frequency, basic_premium, frequency):
    if (start_policy_month_value == 1 and prem_frequency == "S"):
        value = basic_premium
    else:
        try:
            if (start_policy_month_value - 1) % frequency == 0:
                value = 1
            else:
                value
            value = value * basic_premium
        except Exception as e:
            value = 0
    return value

In [38]:
base_premium_first_val(70, 132, 'A', 250000, 12)

0

In [41]:
def base_premium_col(policy_month, total_pol_month, frequency, basic_premium):
    try:
        if (policy_month - 1) % frequency == 0:
            val = 1
        else:
            val = 0
        val = val * basic_premium
    except Exception as e:
        val = 0
    return val

In [42]:
#base_premium_col(73, 132, 12, 250000)

In [43]:
def base_premium_col(policy_month, total_pol_month, frequency, prem_frequency, basic_premium):
    iteration = total_pol_month - policy_month[0]
    base_prem_list = [base_premium_first_val(policy_month[0], total_pol_month, prem_frequency, basic_premium, frequency)]
    for i in range(1, iteration):
        try:
            if (policy_month[i] - 1) % frequency == 0:
                val = 1
            else:
                val = 0
            val = val * basic_premium
            base_prem_list.append(val)
        except Exception as e:
            val = 0
            base_prem_list.append(val)
    return base_prem_list

In [44]:
base_premium = base_premium_col(pol_month_col, 132, 12, 'A', 250000)
#base_premium

## Calculating Allocated Percentage Column

In [45]:
import pandas as pd
def calculating_allocated_percentage(policy_year):
    allocation_list = pd.read_csv("data/assumptions/301/allocation.csv", header=None).squeeze().tolist()
    allocation_percentage_list = []
    for i in range(len(policy_year)):
        year_val = policy_year[i]
        value = allocation_list[year_val - 1] * 100
        allocation_percentage_list.append(value)
    return allocation_percentage_list

In [46]:
allocated_percentage_list = calculating_allocated_percentage(pol_year_col)
#allocated_percentage_list[1:27]
#allocated_percentage_list

### Calculating Allocated Premium Column

In [47]:
def calculating_allocated_premium(base_premium, allocated_percentage):
    allocated_premium_list = []
    for i in range(len(base_premium)):
        value = (base_premium[i] * allocated_percentage[i]) / 100   #allocated_percentage ki value % mai hai jbhe / by 100
        allocated_premium_list.append(value)
    return allocated_premium_list

In [48]:
allocated_premium = calculating_allocated_premium(base_premium, allocated_percentage_list)
#allocated_premium

### Calculating UnAllocated Premium Column

In [49]:
def calculating_unallocated_premium(base_premium, allocated_permium):
    unallocated_premium_list = []
    for i in range(len(base_premium)):
        value = base_premium[i] - allocated_permium[i]
        unallocated_premium_list.append(value)
    return unallocated_premium_list

In [50]:
unallocated_premium = calculating_unallocated_premium(base_premium, allocated_premium)
#unallocated_premium

### Calculating Bid / Offer Charge Column

In [51]:
def calculating_bid_offer_charge(bid_offer_val, allocated_premium):
    bid_offer_charge_list = []
    for i in range(len(allocated_premium)):
        val = allocated_premium[i] * bid_offer_val
        bid_offer_charge_list.append(val)
    return bid_offer_charge_list

In [52]:
bid_offer_charge = calculating_bid_offer_charge(0.00/100, allocated_premium)
#bid_offer_charge

In [53]:
def sum_at_risk_value(death_benefit, sum_assured, CV_BoY_after_premium_val, policy_month_val, total_policy_month):
    if (death_benefit == 2 and policy_month_val < total_policy_month):
        val = max(0, sum_assured - CV_BoY_after_premium_val)
        return val
    else:
        return 0

In [54]:
def mortality_charge_value(CV_BoY_after_premium_val, sum_at_risk_val, mortality_rate_val, mortality_charge_loading):
    if (CV_BoY_after_premium_val <= 0):
        return 0
    else:
        value = mortality_rate_val * sum_at_risk_val * (mortality_charge_loading/100)
        return round(value)
    
mortality_charge_value(238679, 5946, 0.000938, 125)

7

In [55]:
def admin_charge_value(CV_BoY_after_premium_val, admin_charges, admin_inflation, policy_year_val):
    if(CV_BoY_after_premium_val <= 0):
        return 0
    else:
        val = admin_charges * (1 + (admin_inflation/100)) ** (policy_year_val - 1) / 12
        return val

In [56]:
def cash_value_EoY(CV_BoY_after_premium_val, mortality_charge_value, admin_charge_val):
    try:
        value = round(CV_BoY_after_premium_val - mortality_charge_value - admin_charge_val)
    except Exception as e:
        value = 0
    return value

In [57]:
def investment_income(growth_rate_val, cash_value_eoy_val):
    value = round(cash_value_eoy_val * (growth_rate_val/100))
    return value

In [62]:
def cash_value_after_investment_income(cash_value_eoy, investment_income):
    value = cash_value_eoy + investment_income
    return value

In [69]:
def imc(cvai_income_val, imc_val):
    value = (cvai_income_val * (imc_val/100))/12
    return round(value)
    
#imc(237854, 1.75)

In [76]:
def cash_val_eoy_net_of_imc(policy_month_val, total_policy_val, cvai_income_val, imc_val):
    if (policy_month_val > total_policy_val):
        return 0
    else:
        value = cvai_income_val - imc_val
        return value

In [81]:
def sum_at_risk_eoy(policy_month_val, total_policy_month, death_benefit_val, cv_eoy_net_of_imc, sum_assured_val):
    if (policy_month_val >= total_policy_month):
        value = 0
    else:
        if(death_benefit_val == 2):
            value = max(sum_assured_val - cv_eoy_net_of_imc, 0)
        else:
            value = 0
    return value

In [82]:
def policy_holder_account(basic_cash_value, policy_month, total_policy_month, policy_year, sum_assured, death_benefit, mortality_rate, mortality_charge_loading, admin_charges, admin_inflation, growth_rate_val, imc_val):
    iteration = total_policy_month - policy_month[0]
    cash_val_boY = [round(max(basic_cash_value, 0))]
    #base_premium_list = [base_premium_col(policy_month[0], total_policy_month, frequency, base_premium_value)]
    base_premium_list = [base_premium[0]]
    allocated_percentage = [allocated_percentage_list[0]] 
    allocated_premium_list = [allocated_premium[0]] 
    unallocated_premium_list = [unallocated_premium[0]]
    bid_offer_charge_list = [bid_offer_charge[0]]
    CV_BoY_after_premium = [(max(round(allocated_premium[0] + cash_val_boY[0] - bid_offer_charge_list[0]), 0))]
    sum_at_risk_list = [sum_at_risk_value(death_benefit, sum_assured, CV_BoY_after_premium[0], policy_month[0], total_policy_month)]
    mortality_charge_list = [mortality_charge_value(CV_BoY_after_premium[0], sum_at_risk_list[0], mortality_rate[0], mortality_charge_loading)]
    admin_charge_list = [admin_charge_value(CV_BoY_after_premium[0], admin_charges, admin_inflation, policy_year[0])]
    cash_value_EoY_list = [cash_value_EoY(CV_BoY_after_premium[0], mortality_charge_list[0], admin_charge_list[0])]
    investment_income_list = [investment_income(growth_rate_val, cash_value_EoY_list[0])]
    cash_value_after_investment_income_list = [cash_value_after_investment_income(cash_value_EoY_list[0], investment_income_list[0])]
    imc_list = [imc(cash_value_after_investment_income_list[0], imc_val)]
    cash_val_eoy_net_of_imc_list = [cash_val_eoy_net_of_imc(policy_month[0], total_policy_month, cash_value_after_investment_income_list[0], imc_list[0])]
    sum_at_risk_eoy_list = [sum_at_risk_eoy(policy_month[0], total_policy_month, death_benefit, cash_val_eoy_net_of_imc_list[0], sum_assured)]
#     table_data = {
#         'Cash Value at BoY': cash_val_boY[0], 
#         'Base Premium': base_premium_list[0], 
#         'Allocated Percentage': allocated_percentage[0], 
#         'Allocated Premium': allocated_premium_list[0],
#         'UnAllocated Premium': unallocated_premium_list[0],
#         'Bid/Offer Charge': bid_offer_charge_list[0],
#         'CV BoY after Premium': CV_BoY_after_premium[0],
#         'Sum at Risk': sum_at_risk_list[0],
#         'Mortality Charge': mortality_charge_list[0],
#         'Admin Charge': admin_charge_list[0],
#         'Cash Value(EoY)': cash_value_EoY_list[0],
#         'Investment Income': investment_income_list[0]
#         }
#     df = pd.DataFrame(table_data)
#     return df
    return cash_val_boY, base_premium_list, allocated_percentage, allocated_premium_list, unallocated_premium_list, bid_offer_charge_list[0], CV_BoY_after_premium, sum_at_risk_list, mortality_charge_list, admin_charge_list, cash_value_EoY_list, investment_income_list, cash_value_after_investment_income_list, imc_list, cash_val_eoy_net_of_imc_list, sum_at_risk_eoy_list

In [83]:
policy_holder_account(236342.14291912, pol_month_col, 132, pol_year_col, 244625, 2, mortality_rate, 125, 0, 0.00, 0.64, 1.75)

([236342],
 [0],
 [1.0],
 [0.0],
 [0.0],
 0.0,
 [236342],
 [8283],
 [9],
 [0.0],
 [236333],
 [1513],
 [237846],
 [347],
 [237499],
 [7126])

In [3]:
x = {
      "gender": "",
      "admin_inflation": 0.0,
      "bid_offer": 5.0,
      "admin_charges_annual": 0,
      "imc_annual": 1.60,
      "growth_rate": 0.64,
      "surrendered_charges": 350,
      "benefit_type": 2,
      "fixed_expenses": {
          "first_year": 0,
          "second_year": 0,
          "inflation_rate": 0.0,
          "renewal_expense_premium": 0.0,
          "aquisition_expense": 0,
          "admin_expense":0,
          "expected_actual_mortality_charge": 100.0,
          "mortality_charge_loading": 125.0
      },
      "assumptions": {
          "allocation": "data/assumptions/301/allocation.csv",
          "lapse_rate": "data/assumptions/301/lapse_rate.csv",
          "commission": "data/assumptions/301/comission.csv",
          "persistency": "data/assumptions/301/persistency.csv",
          "surrender": "data/assumptions/301/surrender.csv"	
      }
}
    
print(x['fixed_expenses']['aquisition_expense'])

0

In [12]:
value = float("236342,1429".replace(",", "."))
x = value.replace(",", ".")
y = float(x)
print(type(x))
print(type(y))

<class 'str'>
<class 'float'>

In [14]:
value = float("236342,1429".replace(",", "."))
print(type(value))

<class 'float'>

In [24]:
def convert_str_to_float(val):
    #first comma to decimal
    x = val.replace(",", ".")
    #convert x into float value
    return float(x)

In [26]:
y = round(convert_str_to_float("236342,1429"))
print(max(y, 0))

236342

In [34]:
#((1+growth_rate)^(1/12))-1

value = ((1+8)**(1/12))-1
x = value
x

0.20093695517600274

In [2]:
from datetime import date, timedelta

# Replace this with your integer value
integer_value = 23887

# Assuming a reference date, for example, January 1, 1900
reference_date = date(1900, 1, 1)

# Convert the integer to a date
converted_date = reference_date + timedelta(days=integer_value)

print(converted_date)

1965-05-27

In [2]:
x = 39658.79868
print(int(x))

39658

In [3]:
import pandas as pd

value = pd.to_datetime(23887, format='%Y%m%d')
value

#df['DOB'] = pd.to_datetime(df['DOB']).astype(int)

# Convert integer back to DOB
#df['DOB'] = pd.to_datetime(df['DOB'])

ValueError: time data "23887" doesn't match format "%Y%m%d", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [9]:
from datetime import datetime
import pandas as pd

date_object = datetime.strptime(str(23887), '')
pandas_datetime = pd.to_datetime(date_object)
pandas_datetime

ValueError: unconverted data remains: 23887

In [13]:
monthly_interest_rate = ((1 + 0.08) ** (1/12)) - 1
monthly_interest_rate

0.00643403011000343

In [14]:
monthly_interest_rate = ((1 + 8) ** (1/12)) - 1
monthly_interest_rate

0.20093695517600274

## Working on Income Table

In [17]:
x = float(236342,1429)
x

TypeError: float expected at most 1 argument, got 2

In [1]:
from datetime import datetime, timedelta

def months_into_days(comm_date, start_date):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(start_date, "%m/%d/%Y")
#     date_a = datetime.strptime(comm_date, "%d/%m/%Y")
#     date_b = datetime.strptime(start_date, "%d/%m/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

In [2]:
def calculate_policy_month(commencement_date, total_policy_months, start_date):
		policy_month_col = [months_into_days(commencement_date, start_date)]
		total_iterations = total_policy_months - policy_month_col[0]
		for i in range(1, total_iterations):
			if ((policy_month_col[i-1] + 1) < total_policy_months):
				policy_month_col.append(policy_month_col[i-1] + 1)
		return policy_month_col

In [3]:
def cal_policy_year_value(month):
    try:
        result = int(month / 12) + 1
    except ZeroDivisionError:
        result = 0
    return result

In [4]:
def calculate_policy_year(policy_month):
		policy_year_col = []
		for i in range(len(policy_month)):
			policy_year_col.append(cal_policy_year_value(policy_month[i]))
		return policy_year_col

In [5]:
def calculate_age(age, policy_month, policy_year):
    age_column = []
    for i in range(len(policy_month)):
        if policy_month[i] > 0:
            age_val = (age + policy_year[i]) - 1
            age_column.append(age_val)
        else:
            age_column.append(0)
    return age_column

In [6]:
import pandas as pd
def read_csv_to_array(filepath):
    lapse_rate = pd.read_csv(filepath, header=None).squeeze().tolist()
    #print(lapse_rate)
    return lapse_rate

lapse_rate = read_csv_to_array('lapse_rate.csv')

In [8]:
def prepare_base_probablities(lapse_rate, totl_pol_month, commen_date):
#         self.calculate_mortality_rates()
        #total_policies_month = (row['BENEFIT_TERM'] * 12) + 1
        total_policies_month = totl_pol_month + 1
        #commence_date = row['COMMENCEMENT_DATE']
        commence_date = commen_date
        policy_month_list = calculate_policy_month(commence_date, total_policies_month, "1/1/2021")
        policy_year_list = calculate_policy_year(policy_month_list)
        policy_age_list = calculate_age(50, policy_month_list, policy_year_list)
#         mortality_rate_list = self.calculate_mortality_rate(policy_age_list)
#         lapse_rate_list = self.calculate_lapse_rate(policy_year_list, lapse_rate)
#         inforce_at_beginning_and_end_list = self.calculate_inforce_beg_inforce_end(mortality_rate_list, lapse_rate_list, policy_month_list, total_policies_month)
#         inforce_at_beginning_list = inforce_at_beginning_and_end_list[0]
#         inforce_at_end_list = inforce_at_beginning_and_end_list[1]
        #making dataframe column with names and passing list to each column
        table_data = {
           'Policy Month': policy_month_list,
           'Policy Year': policy_year_list,
            'Age': policy_age_list
       }

        df = pd.DataFrame(table_data)
        return df

In [9]:
base_prob_table = prepare_base_probablities(lapse_rate, 192, "1/12/2018")
base_prob_table

     Policy Month  Policy Year  Age
0              37            4   53
1              38            4   53
2              39            4   53
3              40            4   53
4              41            4   53
..            ...          ...  ...
151           188           16   65
152           189           16   65
153           190           16   65
154           191           16   65
155           192           17   66

[156 rows x 3 columns]

In [54]:
def find_next_date(user_provided_date):
    input_date = datetime.strptime(user_provided_date, '%m/%d/%Y')
    next_date = input_date + timedelta(days=1)
    return next_date.strftime('%m/%d/%Y')

find_next_date("12/31/2020")

'01/01/2021'

In [55]:
from datetime import datetime, timedelta

def months_into_days(comm_date, start_date):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(start_date, "%m/%d/%Y")
    diff_in_days = (date_b - date_a).days
    result = round(diff_in_days / 30) + 1
    return result

months_into_days("4/28/2015", "1/1/2021")

70

In [1]:
from datetime import datetime, timedelta

def age_at_comm(comm_date, insure_dob):
    date_a = datetime.strptime(comm_date, "%m/%d/%Y")
    date_b = datetime.strptime(insure_dob, "%m/%d/%Y")
    val_in_days = (date_a - date_b).days + 1
    value_in_years = round((val_in_days /365.25))
    return value_in_years

age_at_comm("4/28/2015", "5/25/1965")

50

In [7]:
from datetime import datetime

def difference_in_years(date1, date2):
    try:
        # Convert the input strings to datetime objects
        date1_obj = datetime.strptime(date1, "%m/%d/%Y")
        date2_obj = datetime.strptime(date2, "%m/%d/%Y")
        
        # Calculate the difference in years
        time_delta = date2_obj - date1_obj
        difference_in_years = time_delta.days / 365.25  # accounting for leap years
        
        return round(difference_in_years)
    except ValueError:
        return "Invalid date format. Please use the format 'YYYY-MM-DD'."

# Example usage:
# date1 = input("Enter the first date (YYYY-MM-DD): ")
# date2 = input("Enter the second date (YYYY-MM-DD): ")
result = difference_in_years("5/25/1965", "4/28/2015")
print("Difference in years:", result)

Difference in years: 50